module.exports = {
  // General errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Authentication errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  
  // Invoice errors
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_ALREADY_FINALIZED: 'INVOICE_ALREADY_FINALIZED',
  INVOICE_CANNOT_BE_EDITED: 'INVOICE_CANNOT_BE_EDITED',
  INVOICE_INVALID_STATUS: 'INVOICE_INVALID_STATUS',
  INVOICE_NUMBER_EXISTS: 'INVOICE_NUMBER_EXISTS',
  
  // Customer errors
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_EMAIL_EXISTS: 'CUSTOMER_EMAIL_EXISTS',
  CUSTOMER_TAX_NUMBER_EXISTS: 'CUSTOMER_TAX_NUMBER_EXISTS',
  CUSTOMER_HAS_INVOICES: 'CUSTOMER_HAS_INVOICES',
  
  // Tax errors
  TAX_CALCULATION_FAILED: 'TAX_CALCULATION_FAILED',
  INVALID_TAX_NUMBER: 'INVALID_TAX_NUMBER',
  TAX_AUTHORITY_ERROR: 'TAX_AUTHORITY_ERROR',
  VAT_SUBMISSION_FAILED: 'VAT_SUBMISSION_FAILED',
  
  // Digital signature errors
  CERTIFICATE_NOT_FOUND: 'CERTIFICATE_NOT_FOUND',
  CERTIFICATE_EXPIRED: 'CERTIFICATE_EXPIRED',
  CERTIFICATE_REVOKED: 'CERTIFICATE_REVOKED',
  SIGNATURE_INVALID: 'SIGNATURE_INVALID',
  SIGNATURE_CREATION_FAILED: 'SIGNATURE_CREATION_FAILED',
  
  // PEPPOL errors
  PEPPOL_GATEWAY_ERROR: 'PEPPOL_GATEWAY_ERROR',
  PEPPOL_PARTICIPANT_INVALID: 'PEPPOL_PARTICIPANT_INVALID',
  PEPPOL_SUBMISSION_FAILED: 'PEPPOL_SUBMISSION_FAILED',
  PEPPOL_DOCUMENT_INVALID: 'PEPPOL_DOCUMENT_INVALID',
  
  // Database errors
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  DATABASE_QUERY_ERROR: 'DATABASE_QUERY_ERROR',
  DATABASE_CONSTRAINT_ERROR: 'DATABASE_CONSTRAINT_ERROR',
  
  // File errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_INVALID_FORMAT: 'FILE_INVALID_FORMAT',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  
  // Email errors
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  EMAIL_TEMPLATE_ERROR: 'EMAIL_TEMPLATE_ERROR',
  EMAIL_CONFIGURATION_ERROR: 'EMAIL_CONFIGURATION_ERROR',
  
  // Report errors
  REPORT_GENERATION_FAILED: 'REPORT_GENERATION_FAILED',
  REPORT_EXPORT_FAILED: 'REPORT_EXPORT_FAILED',
  REPORT_DATA_INVALID: 'REPORT_DATA_INVALID'
};
